# Generated by Django 5.2.11 on 2026-05-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Platform Admin'), ('tenant', 'Tenant (Business Owner)'), ('staff', 'Staff (Store Employee)')], default='tenant', max_length=20),
        ),
    ]
