# Generated by Django 5.2.11 on 2026-04-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_type',
            field=models.CharField(choices=[('grocery', 'Grocery Store'), ('pharmacy', 'Pharmacy & Medicine'), ('electronics', 'Electronics & Gadgets'), ('clothing', 'Clothing & Apparel'), ('general', 'General Retail'), ('other', 'Other')], default='general', max_length=50),
        ),
    ]
