# Generated by Django 5.2.11 on 2026-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.CharField(blank=True, help_text='e.g., my-shop (optional, for future use)', max_length=100, null=True, unique=True),
        ),
    ]
