# Generated by Django 5.2.11 on 2026-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_tenant_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
