# Generated by Django 5.2.11 on 2026-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Available variants/colors', null=True),
        ),
    ]
