# Generated by Django 5.2.11 on 2026-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacities',
            field=models.JSONField(blank=True, default=list, help_text='Available capacities and prices', null=True),
        ),
    ]
