# Generated by Django 5.2.11 on 2026-05-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_capacities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='capacities',
            field=models.JSONField(blank=True, default=list, help_text="Available capacities and prices e.g. [{name:'1L', price:500}]", null=True),
        ),
    ]
