# Generated by Django 5.2.11 on 2026-04-15 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='ProductSpecification',
        ),
    ]
