# Generated by Django 5.2.11 on 2026-04-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_productspecification_product_delete_feature_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='is_featured',
            new_name='is_ai_flagged',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='original_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_on_sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='product',
            name='predicted_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
