# Generated by Django 5.2.11 on 2026-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_best_before_days',
            field=models.PositiveIntegerField(default=0, help_text='Default number of days before products in this category expire'),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='expiry_strategy',
            field=models.CharField(choices=[('PERISHABLE', 'Perishable (Fresh Foods)'), ('STABLE', 'Stable (Canned, Biscuits)'), ('MEDICAL', 'Medical (Drugs, Medications)'), ('GENERAL', 'General (Non-food items)')], default='GENERAL', max_length=20),
        ),
    ]
