# Generated by Django 5.2.11 on 2026-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_tenant_product_tenant_productimage_tenant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['business_type', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='business_type',
            field=models.CharField(choices=[('grocery', 'Grocery & Provisions'), ('pharmacy', 'Pharmacy & Medicine'), ('electronics', 'Electronics & Gadgets'), ('clothing', 'Clothing & Apparel'), ('general', 'General Retail'), ('other', 'Other')], db_index=True, default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='default_best_before_days',
            field=models.PositiveIntegerField(default=0, help_text='Default number of days before products in this category expire (0 = no default)'),
        ),
    ]
