# Generated by Django 5.2.11 on 2026-05-19 07:35

from django.db import migrations


def seed_categories(apps, schema_editor):
    """
    Seed global (tenant=None) preset categories for every business type.
    Idempotent — uses get_or_create so re-running is safe.
    """
    Category = apps.get_model('products', 'Category')

    presets = {
        'grocery': [
            {'name': 'Grains & Cereals',      'expiry_strategy': 'STABLE',     'default_best_before_days': 365},
            {'name': 'Dairy & Eggs',           'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 14},
            {'name': 'Meat & Poultry',         'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 5},
            {'name': 'Fish & Seafood',         'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 3},
            {'name': 'Fruits & Vegetables',    'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 7},
            {'name': 'Bread & Bakery',         'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 5},
            {'name': 'Canned & Preserved',     'expiry_strategy': 'STABLE',     'default_best_before_days': 730},
            {'name': 'Cooking Oils & Fats',    'expiry_strategy': 'STABLE',     'default_best_before_days': 540},
            {'name': 'Spices & Seasonings',    'expiry_strategy': 'STABLE',     'default_best_before_days': 730},
            {'name': 'Snacks & Confectionery', 'expiry_strategy': 'STABLE',     'default_best_before_days': 180},
            {'name': 'Beverages',              'expiry_strategy': 'STABLE',     'default_best_before_days': 365},
            {'name': 'Household & Cleaning',   'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Baby & Infant',          'expiry_strategy': 'STABLE',     'default_best_before_days': 365},
            {'name': 'Frozen Foods',           'expiry_strategy': 'PERISHABLE', 'default_best_before_days': 90},
        ],
        'pharmacy': [
            {'name': 'Prescription Drugs',     'expiry_strategy': 'MEDICAL',    'default_best_before_days': 730},
            {'name': 'Over-the-Counter (OTC)', 'expiry_strategy': 'MEDICAL',    'default_best_before_days': 730},
            {'name': 'Vitamins & Supplements', 'expiry_strategy': 'MEDICAL',    'default_best_before_days': 365},
            {'name': 'First Aid & Wound Care', 'expiry_strategy': 'MEDICAL',    'default_best_before_days': 1095},
            {'name': 'Medical Devices',        'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Personal Care',          'expiry_strategy': 'GENERAL',    'default_best_before_days': 730},
            {'name': 'Baby & Maternal Health', 'expiry_strategy': 'MEDICAL',    'default_best_before_days': 365},
            {'name': 'Eye & Ear Care',         'expiry_strategy': 'MEDICAL',    'default_best_before_days': 365},
            {'name': 'Dermatology & Skin',     'expiry_strategy': 'GENERAL',    'default_best_before_days': 730},
            {'name': 'Oral Health',            'expiry_strategy': 'GENERAL',    'default_best_before_days': 730},
        ],
        'electronics': [
            {'name': 'Smartphones & Tablets',  'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Laptops & Computers',    'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Audio & Headphones',     'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Cameras & Photography',  'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'TV & Home Theatre',      'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Accessories & Cables',   'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Power & Batteries',      'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Smart Home',             'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Gaming',                 'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Networking',             'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
        ],
        'clothing': [
            {'name': "Men's Wear",             'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': "Women's Wear",           'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': "Children's Wear",        'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Footwear',               'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Accessories & Bags',     'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Sportswear & Activewear','expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Underwear & Lingerie',   'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Traditional & Ethnic',   'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Formal & Office Wear',   'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
        ],
        'general': [
            {'name': 'Miscellaneous',          'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Stationery & Office',    'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Tools & Hardware',       'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
            {'name': 'Home & Kitchen',         'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
        ],
        'other': [
            {'name': 'Uncategorised',          'expiry_strategy': 'GENERAL',    'default_best_before_days': 0},
        ],
    }

    for business_type, categories in presets.items():
        for cat in categories:
            Category.objects.get_or_create(
                name=cat['name'],
                business_type=business_type,
                tenant=None,
                defaults={
                    'expiry_strategy': cat['expiry_strategy'],
                    'default_best_before_days': cat['default_best_before_days'],
                }
            )


def unseed_categories(apps, schema_editor):
    """Remove all seeded global (tenant=None) preset categories."""
    Category = apps.get_model('products', 'Category')
    Category.objects.filter(tenant__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_business_type_to_category'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_code=unseed_categories),
    ]
