# Generated by Django 5.2.11 on 2026-05-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_customer_sale_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='variant',
            field=models.CharField(blank=True, help_text='Selected product variant', max_length=100, null=True),
        ),
    ]
