# Generated by Django 5.2.11 on 2026-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_saleitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='capacity',
            field=models.CharField(blank=True, help_text='Selected product capacity', max_length=100, null=True),
        ),
    ]
